name: Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo ${{ secrets.REPO_SECRET }}
          echo ${{ secrets.REPO_SECRET }} >> log.txt
          cat log.txt

      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt
