name: Dev

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    # environment: Production
    
    steps:
      - name: secrets
        run: |
          echo ${{ secrets.PROD_SECRET }}
          echo ${{ secrets.PROD_SECRET }} >> log.txt
          
          echo ${{ secrets.REPO_SECRET }}
          #echo ${{ secrets.REPO_SECRET }} >> log.txt
          
          cat log.txt

      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt
