name: Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo ${{ vars.HAS_DB }}
          echo ${{ secrets.DB_PASSWORD }}
          echo ${{ secrets.DB_PASSWORD }} > log.txt
          cat log.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: log.txt
