name: Dev

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v3

      - name: test
        run:
          echo Testing.

      - name: build
        run: |
          echo Getting libs,
          echo and building.
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo Deploying to Dev environment.

  wiki:
    needs: deploy
    uses: bromba-noesis/wiki/.github/workflows/wiki_project_update.yml@main
    with:
      myEnvironment: Development
    secrets: inherit
