name: Dev

on:
  workflow_dispatch:

jobs:          
  deploy:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3 
        if: ${{ vars.HAS_DB == 'true' }}

      - uses: liquibase-github-actions/update@v4.23.1
        if: ${{ vars.HAS_DB == 'true' }}
        with:
          changelogFile: liquibase/changelog.xml
          url: jdbc:sqlserver://azsql0.database.windows.net:1433;database=mySQLdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
          defaultSchemaName: mySQLdb
          username: adminLogin@azsql0
          password: "${{ secrets.DB_PASSWORD }}"
