name: Dev

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: test
        run:
          echo Testing.

      - name: build
        run: |
          echo Getting libs,
          echo and building.
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: deploy
        run: echo Deploying to Dev environment.
