name: Prod

on:
  workflow_dispatch:

jobs:          
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: approve/reject
        run: echo Approving/rejecting.
  
      - name: deploy
        run: echo Deploying to Prod environment.

  report:
    needs: deploy
    uses: bromba-noesis/wiki/.github/workflows/wiki_project_update.yml@main
    with:
      myEnvironment: Production
    secrets: inherit
