name: Prod

on:
  workflow_dispatch:

jobs:     
  approve:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: approve/reject
        run: echo Approving/rejecting.
  deploy:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: approve/reject
        run: echo Approving/rejecting.
  
      - name: deploy
        run: echo Deploying to Prod environment.

  wiki:
    needs: deploy
    uses: bromba-noesis/wiki/.github/workflows/wiki_project_update.yml@main
    with:
      myEnvironment: Production
    secrets: inherit
