name: Qua

on:
  push:
    branches: [ "release/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: analyze
        run:
          echo Analyzing.

      - name: build
        run: |
          echo Getting libs,
          echo and building.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Quality

    steps:
      - name: deploy
        run: echo Deploying to Qua environment.
