name: Qua

on:
  push:
    branches: [ "release/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Quality

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: echo Testing.

      - name: build
        run: echo Building.

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy binaries        
        run: echo Deploying binaries to Qua environment.
      - name: deploy db
        if: ${{ github.HAS_QUA_DB == 'true' }}
        run: echo Deploying to Qua DB.

  wiki:
    needs: deploy
    uses: bromba-noesis/wiki/.github/workflows/wiki_project_update.yml@main
    with:
      myEnvironment: Quality
    secrets: inherit
