name: Wiki

on: 
    workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          echo "myDate=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "myHour=$(date +'%H:%M:%S')" >> $GITHUB_ENV
          echo "myCID=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "myBranch=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "myTag=$GITHUB_REF_NAME" >> $GITHUB_ENV
