name: Wiki

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Date
        run: echo "mydate=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Hour
        run: |
          echo $mydate
          echo $(date +'%H:%M:%S')
      - name: Branch name
        run: echo ${GITHUB_REF##*/}
      - name: Commit ID
        run: echo ${GITHUB_SHA}
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
